build:
  image: ruby:2.4.2
  commands:
    - curl -o /usr/bin/framgia-ci https://raw.githubusercontent.com/framgia/ci-report-tool/master/dist/framgia-ci && chmod +x /usr/bin/framgia-ci
    - apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs
    - gem install rails -v 5.1.6
    - cp config/database-ci.yml config/database.yml
    - ruby --version
    - bundle install
    # - sleep 60
    - framgia-ci test-connect 127.0.0.1 3306
    # - apt-get install telnet
    # - telnet 127.0.0.1 3306
    - RAILS_ENV=test rake db:create db:migrate
    - framgia-ci run
compose:
  database:
    image: mysql:5.7
    restart: always
    expose:
      - "3306"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ci
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: root
  redis:
    image: redis:3.0.7
cache:
  mount:
    - .git
